export const currencies = [
  { code: 'USD', country: 'US' },
  { code: 'EUR', country: 'EU' },
  { code: 'GBP', country: 'GB' },
  { code: 'JPY', country: 'JP' },
  { code: 'CAD', country: 'CA' },
  { code: 'AUD', country: 'AU' },
  { code: 'CHF', country: 'CH' },
  { code: 'CNY', country: 'CN' },
  { code: 'INR', country: 'IN' },
  { code: 'BDT', country: 'BD' },
  { code: 'NPR', country: 'NP' },
  { code: 'MXN', country: 'MX' },
  { code: 'KRW', country: 'KR' },
  { code: 'SEK', country: 'SE' },
  { code: 'NZD', country: 'NZ' },
  { code: 'SGD', country: 'SG' },
  { code: 'HKD', country: 'HK' },
  { code: 'HUF', country: 'HU' },
  { code: 'BRL', country: 'BR' },
  { code: 'HRK', country: 'HR' },
];
