"use client";
import { useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, ArrowUpRight, CalendarDays, MapPin, Users, Plus, Plane, Hotel, Coffee, Compass, Wallet, Check, Package, Trash2, ThumbsUp, Lightbulb, Route, Pencil, Download, Sparkles, Heart, X, Ticket, Bot } from 'lucide-react';
import { ItineraryItem, useTripStore } from '@/store/useTripStore';
import BookingsPanel from '@/components/BookingsPanel';
import AssistantPanel from '@/components/AssistantPanel';
import { removeTicket } from '@/lib/ticket-files';
import TopbarUser from '@/components/TopbarUser';
import Modal from '@/components/Modal';
import TripForm from '@/components/TripForm';
import { dateLabel, downloadFile, localDate, money, tripStatus } from '@/lib/travel';
type Tab = 'itinerary' | 'expenses' | 'packing' | 'ideas' | 'bookings' | 'assistant';
type FormKind = Exclude<Tab,'bookings'|'assistant'> | 'starter' | 'delete' | null;
const categoryIcons = { activity: Compass, food: Coffee, transport: Plane, hotel: Hotel };
const starterActivities: Record<string, { title: string; time: string; category: ItineraryItem['category'] }[]> = {
  Relaxed: [{ title: 'Arrive, settle in & take it slow', time: '14:00', category: 'hotel' }, { title: 'A slow morning & a local café', time: '10:00', category: 'food' }, { title: 'Explore at your own pace', time: '11:00', category: 'activity' }],
  Adventure: [{ title: 'Arrive & prepare for the adventure', time: '14:00', category: 'hotel' }, { title: 'Discover a scenic walking route', time: '08:00', category: 'activity' }, { title: 'Explore the outdoors', time: '09:00', category: 'activity' }],
  Culture: [{ title: 'Arrive & explore the neighborhood', time: '14:00', category: 'activity' }, { title: 'Visit a museum or local landmark', time: '10:00', category: 'activity' }, { title: 'Find a local market & try something new', time: '11:00', category: 'food' }],
};
export default function TripPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter();
  const store = useTripStore(); const trip = store.trips.find(t => t.id === id);
  const plans = store.itinerary.filter(i => i.tripId === id).sort((a,b) => a.date.localeCompare(b.date) || a.time.localeCompare(b.time));
  const expenses = store.expenses.filter(e => e.tripId === id);
  const packing = store.packingList.filter(p => p.tripId === id);
  const ideas = store.ideas.filter(i => i.tripId === id);
  const bookings = store.bookings.filter(b => b.tripId === id);
  const [tab, setTab] = useState<Tab>('itinerary'); const [modal, setModal] = useState<FormKind>(null); const [editing, setEditing] = useState(false);
  const [expensePer, setExpensePer] = useState<'group'|'person'>('group');
  const [editPlanId, setEditPlanId] = useState<string | null>(null);
  const [notice, setNotice] = useState(''); const [day, setDay] = useState('all'); const [style, setStyle] = useState('Relaxed');
  const [form, setForm] = useState({ title: '', date: '', time: '10:00', category: 'activity', location: '', estimatedCost: '', amount: '', person: 'You', description: '' });
  const total = expenses.reduce((sum,e) => sum + e.amount, 0); const packed = packing.filter(p => p.isCompleted).length;
  if (!trip) return <div className="not-found"><Compass size={40}/><h1>This adventure isn’t here.</h1><p className="muted">It may have been removed or saved on another device.</p><Link className="button primary" href="/">Back to your workspace <ArrowUpRight size={17}/></Link></div>;
  const currency = trip.currency || 'USD'; const budget = trip.budget || 0;
  const days = [...new Set(plans.map(p => p.date))];
  function openForm(kind: FormKind) { setEditPlanId(null); setForm({ title: '', date: trip?.startDate || localDate(), time: '10:00', category: 'activity', location: trip?.destination || '', estimatedCost: '', amount: '', person: 'You', description: '' }); setModal(kind); }
  function save(e: React.FormEvent) {
    e.preventDefault(); if (!form.title.trim()) return;
    if (modal === 'itinerary') { const data = { tripId: id, title: form.title.trim(), date: form.date, time: form.time, category: form.category as ItineraryItem['category'], location: form.location.trim(), estimatedCost: form.estimatedCost.trim() || 'Not estimated' }; if (editPlanId) store.updateItineraryItem(editPlanId, data); else store.addItineraryItem(data); }
    if (modal === 'expenses') { let amount = Number(form.amount); if (!Number.isFinite(amount) || amount <= 0) return; if (expensePer === 'person') amount = amount * (trip.members || 1); store.addExpense({ tripId: id, title: form.title.trim(), amount, paidBy: form.person.trim() || 'You', date: form.date }); }
    if (modal === 'packing') store.addPackingItem({ tripId: id, title: form.title.trim(), assignedTo: form.person.trim() || 'You' });
    if (modal === 'ideas') store.addIdea({ tripId: id, title: form.title.trim(), description: form.description.trim(), author: form.person.trim() || 'You' });
    setModal(null); setNotice('Added to your adventure.');
  }
  function addStarter() {
    if (!trip) return;
    const start = new Date((trip.startDate || localDate()) + 'T12:00:00');
    const length = trip.startDate && trip.endDate ? Math.max(1, Math.round((new Date(trip.endDate + 'T12:00:00').getTime() - start.getTime()) / 86400000) + 1) : 3;
    starterActivities[style].slice(0, length).forEach((item,index) => {
      const date = new Date(start); date.setDate(date.getDate() + index); const dateString = localDate(date);
      if (!plans.some(p => p.title === item.title && p.date === dateString)) store.addItineraryItem({ ...item, tripId: id, date: dateString, location: trip.destination, estimatedCost: 'Not estimated' });
    });
    const items = ['Travel documents', 'Phone & charger', 'Personal essentials', 'Comfortable shoes', style === 'Adventure' ? 'Daypack & water bottle' : style === 'Relaxed' ? 'A book for the slow moments' : 'Notebook & camera'];
    items.filter(title => !packing.some(p => p.title.toLowerCase() === title.toLowerCase())).forEach(title => store.addPackingItem({ tripId: id, title, assignedTo: 'You' }));
    setModal(null); setNotice('Your starter is ready. Customize the details to make it yours.');
  }
  const icons = { itinerary: Route, expenses: Wallet, packing: Package, ideas: Lightbulb, bookings: Ticket, assistant: Bot };
  const counts = { itinerary: plans.length, expenses: expenses.length, packing: packing.length, ideas: ideas.length, bookings: bookings.length, assistant: 0 };
  const tabLabels = { itinerary: 'Itinerary', expenses: 'Budget & expenses', packing: 'Packing list', ideas: 'Ideas board', bookings: 'Bookings & tickets', assistant: 'AI assistant' };
  const addLabels = { itinerary: 'Add a plan', expenses: 'Add expense', packing: 'Add an item', ideas: 'Add an idea' };
  return <main className="dashboard detail-page">
    <div className="topbar"><div className="breadcrumb"><Link href="/">Your workspace</Link><span>/</span><strong>Trip planner</strong></div><div className="topbar-actions"><button className="icon-button" onClick={() => store.updateTrip(id, { favorite: !trip.favorite })} aria-label={trip.favorite ? 'Unsave trip' : 'Save trip'} aria-pressed={!!trip.favorite}><Heart size={18} fill={trip.favorite ? 'currentColor' : 'none'}/></button><button className="icon-button" onClick={() => setModal('delete')} aria-label="Delete trip"><Trash2 size={17}/></button><TopbarUser /></div></div>
    <section className="detail-hero" style={{ backgroundImage: `url(${trip.image})` }}><div className="detail-hero-top"><Link href="/?view=trips" className="button"><ArrowLeft size={15}/>Your adventures</Link><button className="button" onClick={() => setEditing(true)}><Pencil size={14}/>Edit trip</button></div><div className="detail-hero-copy"><span className="status-pill">{tripStatus(trip)}</span><h1>{trip.title}</h1><div className="detail-hero-meta"><span><MapPin size={14}/>{trip.destination}</span><span><CalendarDays size={14}/>{trip.dates}</span><span><Users size={14}/>{trip.members} {trip.members === 1 ? 'traveler' : 'travelers'}</span></div></div></section>
    <section className="detail-summary"><div className="summary-card"><span><Route size={15}/>Moments planned</span><h3>{String(plans.length).padStart(2,'0')} <small className="muted" style={{ fontSize: 11 }}>across {days.length} {days.length === 1 ? 'day' : 'days'}</small></h3><p>A little structure. Plenty of possibility.</p></div><div className="summary-card"><span><Wallet size={15}/>Trip spending · {currency}</span><h3>{money(total,currency)}</h3><p>{budget ? `${money(Math.abs(budget-total),currency)} ${total > budget ? 'over budget' : 'left to enjoy'}` : 'Add a budget in Edit trip'}</p>{budget > 0 && <div className={`progress-track ${total > budget ? 'over' : ''}`}><span style={{ width: Math.min(100,total / budget * 100) + '%' }}/></div>}</div><div className="summary-card"><span><Package size={15}/>Ready for takeoff</span><h3>{packed}<small className="muted" style={{ fontSize: 12 }}> / {packing.length} packed</small></h3><div className="progress-track"><span style={{ width: (packing.length ? packed / packing.length * 100 : 0) + '%' }}/></div></div></section>
    {trip.description && <p className="detail-notes">{trip.description}</p>}
    <nav className="detail-tabs" aria-label="Trip sections">{(['itinerary','bookings','expenses','packing','ideas','assistant'] as Tab[]).map(t => { const Icon = icons[t]; return <button key={t} className={tab === t ? 'active' : ''} onClick={() => setTab(t)} aria-current={tab === t ? 'page' : undefined}><Icon size={17}/>{tabLabels[t]}{t !== "assistant" && <span className="count-badge">{counts[t]}</span>}</button>; })}</nav>
    {tab === "bookings" && <BookingsPanel trip={trip}/>}
    {tab === "assistant" && <AssistantPanel trip={trip}/>}
    {(tab !== "bookings" && tab !== "assistant") && <section className="detail-content"><div className="section-heading"><div><h2>{tabLabels[tab]}</h2><p>{tab === 'itinerary' ? 'The best days have a little room for the unexpected.' : tab === 'expenses' ? 'Keep the numbers simple. Focus on the memories.' : tab === 'packing' ? 'A little preparation goes a long way.' : 'Keep your maybes, must-dos, and brilliant little ideas here.'}</p></div><div className="detail-actions">{(tab === 'itinerary' || tab === 'packing') && <button className="button secondary" onClick={() => setModal('starter')}><Sparkles size={15}/>Trip starter</button>}<button className="button primary" onClick={() => openForm(tab)}><Plus size={16}/>{addLabels[tab]}</button></div></div>
    {tab === 'itinerary' && <>{days.length > 1 && <div className="filter-tabs"><button className={day === 'all' ? 'active' : ''} onClick={() => setDay('all')}>All days</button>{days.map(d => <button key={d} className={day === d ? 'active' : ''} onClick={() => setDay(d)}>{/^\d{4}-\d{2}-\d{2}$/.test(d) ? dateLabel(d) : d}</button>)}</div>}{plans.length ? days.filter(d => day === 'all' || day === d).map(d => <div key={d}><div className="timeline-day"><CalendarDays size={16}/>{/^\d{4}-\d{2}-\d{2}$/.test(d) ? dateLabel(d) : d}</div>{plans.filter(p => p.date === d).map(p => { const Icon = categoryIcons[p.category] || Compass; return <article className="plan-row" key={p.id}><span className="plan-time">{p.time}</span><span className="plan-icon"><Icon size={19}/></span><div className="plan-info"><h3>{p.title}</h3><p><MapPin size={12}/>{p.location || trip.destination}</p></div><span className="plan-cost">{p.estimatedCost}</span><button className="icon-button" aria-label={`Edit plan ${p.title}`} onClick={() => { setEditPlanId(p.id); setForm({ title: p.title, date: /^\d{4}-\d{2}-\d{2}$/.test(p.date) ? p.date : trip.startDate || localDate(), time: /^\d{2}:\d{2}$/.test(p.time) ? p.time : "10:00", category: p.category, location: p.location, estimatedCost: p.estimatedCost, amount: "", person: "You", description: "" }); setModal("itinerary"); }}><Pencil size={14}/></button><button className="icon-button" aria-label={`Remove ${p.title}`} onClick={() => { store.deleteItineraryItem(p.id); setDay('all'); }}><Trash2 size={14}/></button></article>; })}</div>) : <Empty icon={<Route/>} title="Make room for memorable days." text="Add your own plans, or use a trip starter for an itinerary and packing checklist you can make your own."/>}</>}
    {tab === 'expenses' && <>{trip.budgetPlan && trip.budgetPlan.currency === currency && <div className="saved-budget"><div className="section-heading"><h3>Your budget plan</h3><span className="privacy-chip">AI draft · saved by you</span></div>{trip.budgetPlan.categories.map((c,i)=><div className="proposed-budget" key={i}><div><strong>{c.name}</strong><p>{c.reason}</p></div><strong>{money(c.amount,currency)}</strong></div>)}</div>}<div className="detail-summary"><div className="summary-card"><span>Total spent</span><h3>{money(total,currency)}</h3></div><div className="summary-card"><span>Equal share per traveler</span><h3>{money(total / Math.max(1,trip.members),currency)}</h3><p>Planning estimate, not a settlement.</p></div><div className="summary-card"><span>Trip budget</span><h3>{budget ? money(budget,currency) : 'Not set'}</h3><button className="text-link" onClick={() => setEditing(true)}>Adjust budget <Pencil size={11}/></button></div></div>{expenses.length ? <div className="expense-list">{expenses.map(e => <article className="expense-row" key={e.id}><span className="plan-icon"><Wallet size={18}/></span><div className="plan-info"><h3>{e.title}</h3><p>Paid by {e.paidBy} · {e.date}</p></div><span className="expense-value">{money(e.amount,currency)}</span><button className="icon-button" onClick={() => store.deleteExpense(e.id)} aria-label={`Delete expense ${e.title}`}><Trash2 size={14}/></button></article>)}</div> : <Empty icon={<Wallet/>} title="Good times, clear numbers." text="Add flights, stays, meals, and everything in between. Your total and equal share update automatically."/>}<p className="muted micro">Amounts are recorded in {currency}. Changing your trip currency changes the label; it does not convert previous amounts.</p></>}
    {tab === 'packing' && <>{packing.length ? <>{packing.map(item => <article className="packing-row" key={item.id}><button className={`packing-check ${item.isCompleted ? 'checked' : ''}`} role="checkbox" aria-checked={item.isCompleted} aria-label={`Packed: ${item.title}`} onClick={() => store.togglePackingItem(item.id)}>{item.isCompleted && <Check size={16}/>}</button><div className={`plan-info ${item.isCompleted ? 'completed' : ''}`}><h3>{item.title}</h3><p>{item.assignedTo}</p></div><button className="icon-button" onClick={() => store.deletePackingItem(item.id)} aria-label={`Remove ${item.title}`}><Trash2 size={14}/></button></article>)}</> : <Empty icon={<Package/>} title="Pack light. Feel ready." text="Create your checklist, assign items to travelers, and check things off as you go."/>}</>}
    {tab === 'ideas' && <>{ideas.length ? <div className="idea-grid">{[...ideas].sort((a,b) => b.votes - a.votes).map(i => <article className="idea-card" key={i.id}><h3>{i.title}</h3><p>{i.description || 'A possibility worth keeping.'}</p><footer><small>By {i.author}</small><button className="idea-vote" aria-label={`Add a vote for ${i.title}`} onClick={() => store.voteIdea(i.id)}><ThumbsUp size={13}/>{i.votes}</button><button className="icon-button" onClick={() => store.deleteIdea(i.id)} aria-label={`Delete idea ${i.title}`}><Trash2 size={13}/></button></footer></article>)}</div> : <Empty icon={<Lightbulb/>} title="Save a little possibility." text="A tucked-away café, a sunrise hike, a place someone mentioned. Give your ideas a home."/>}<p className="muted micro">Ideas and votes are shared on this device. Each tap adds one vote.</p></>}
    </section>}
    {editing && <TripForm trip={trip} onClose={() => setEditing(false)}/>}
    {modal && modal !== 'starter' && modal !== 'delete' && <Modal title={editPlanId && modal === "itinerary" ? "Edit your plan" : addLabels[modal]} subtitle="One more detail to look forward to." onClose={() => setModal(null)}><form className="form-stack" onSubmit={save}><label>{modal === 'packing' ? 'Item name' : 'Title'}<input autoFocus required maxLength={160} value={form.title} placeholder={modal === 'itinerary' ? 'e.g. Coffee & a neighborhood wander' : modal === 'expenses' ? 'e.g. Train tickets' : modal === 'packing' ? 'e.g. Passport' : 'e.g. A sunset picnic'} onChange={e => setForm({ ...form, title: e.target.value })}/></label>
    {modal === 'itinerary' && <><div className="form-grid"><label>Date<input type="date" required min={trip.startDate} max={trip.endDate} value={form.date} onInput={e => setForm({ ...form, date: e.currentTarget.value })}/></label><label>Time<input type="time" required value={form.time} onInput={e => setForm({ ...form, time: e.currentTarget.value })}/></label></div><div className="form-grid"><label>Category<select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}><option value="activity">Explore & experience</option><option value="food">Food & drink</option><option value="hotel">Stay & rest</option><option value="transport">Getting around</option></select></label><label>Estimated cost ({currency})<input maxLength={50} placeholder="e.g. 25 USD or Free" value={form.estimatedCost} onChange={e => setForm({ ...form, estimatedCost: e.target.value })}/></label></div><label>Location<input maxLength={150} value={form.location} onChange={e => setForm({ ...form, location: e.target.value })}/></label></>}
    {modal === 'expenses' && <div className="form-grid"><label>Amount ({currency}) <select style={{display:'inline', width:'auto', padding:'2px 4px', fontSize:'9px', marginLeft:'6px', background: 'var(--canvas)', border: '1px solid var(--line)', borderRadius: '4px', color: 'var(--muted)'}} value={expensePer} onChange={e=>setExpensePer(e.target.value as 'group'|'person')}><option value="group">Total</option><option value="person">Per traveler</option></select><input type="number" required min="0.01" step="0.01" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })}/></label><label>Date<input type="date" required value={form.date} onInput={e => setForm({ ...form, date: e.currentTarget.value })}/></label></div>}
    {modal === 'ideas' && <label>Notes<textarea rows={4} maxLength={1500} placeholder="What makes it worth a visit?" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })}/></label>}
    {modal !== 'itinerary' && <label>{modal === 'expenses' ? 'Paid by' : modal === 'packing' ? 'Assigned to' : 'Suggested by'}<input required maxLength={80} value={form.person} onChange={e => setForm({ ...form, person: e.target.value })}/></label>}
    <div className="modal-footer"><button type="button" className="button secondary" onClick={() => setModal(null)}>Cancel</button><button className="button primary" type="submit">Save to trip <Check size={16}/></button></div></form></Modal>}
    {modal === 'starter' && <Modal title="Give your plans a head start." subtitle="A simple, editable template. No reservations or live recommendations." onClose={() => setModal(null)}><div className="form-stack"><div className="starter-options">{Object.keys(starterActivities).map(s => <button className={`starter-option ${style === s ? 'selected' : ''}`} aria-pressed={style === s} key={s} onClick={() => setStyle(s)}>{s}</button>)}</div><div className="starter-preview"><strong>Your first days, thoughtfully paced.</strong>{starterActivities[style].map((p,i) => <p key={p.title}>Day {i+1} · {p.title}</p>)}<br/><strong>Plus an essentials packing checklist.</strong><p>Starts on {dateLabel(trip.startDate || localDate())}. Short trips receive only the days that fit. Existing matching items are skipped.</p></div><div className="modal-footer"><button className="button secondary" onClick={() => setModal(null)}>Maybe later</button><button className="button primary" onClick={addStarter}><Sparkles size={16}/>Add to my trip</button></div></div></Modal>}
    {modal === 'delete' && <Modal title="Let this adventure go?" subtitle="This removes this trip, bookings, ticket files, plans, expenses, packing items, ideas, and AI conversation from this device." onClose={() => setModal(null)}><p>Delete <strong>{trip.title}</strong>?</p><div className="modal-footer"><button className="button secondary" onClick={() => setModal(null)}>Keep trip</button><button className="button danger" onClick={async () => { try { await Promise.all(bookings.flatMap(b => b.attachments).map(f => removeTicket(f.id))); store.deleteTrip(id); router.push('/'); } catch { setNotice('Could not remove ticket files. Please try again.'); } }}>Delete trip</button></div></Modal>}
    {notice && <div className="toast" role="status">{notice}<button onClick={() => setNotice('')} aria-label="Dismiss notification"><X size={15}/></button></div>}
  </main>;
}
function Empty({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="detail-empty">{icon}<h3>{title}</h3><p>{text}</p></div>; }
